import { constructHtmlBoilerplate } from '@/lib/utils/html-boilerplate'
import { readFileSync } from 'fs'
import { join } from 'path'

export interface ExportOptions {
  businessName: string
  industry?: string
  description?: string
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

/**
 * Read the preview runtime script and cache it in memory.
 * Inlined into exported HTML so it works as a standalone file.
 */
let cachedRuntime: string | null = null
function getRuntime(): string {
  if (!cachedRuntime) {
    cachedRuntime = readFileSync(
      join(process.cwd(), 'public', 'preview-runtime.js'),
      'utf-8'
    )
  }
  return cachedRuntime
}

/**
 * Builds a self-contained static HTML export from generated React code.
 *
 * Inlines the preview runtime so the file works when opened locally
 * (no server needed). Adds metadata for standalone use.
 */
export function buildStaticExport(generatedCode: string, options: ExportOptions): string {
  // Use a dummy runtime URL — we'll replace the loader script with inlined code
  let html = constructHtmlBoilerplate(generatedCode)

  // 1. Add generated-by comment after DOCTYPE
  html = html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- Generated by WebGen -->')

  // 2. Replace the <title>Preview</title> with business name
  const titleSuffix = options.industry ? ' | ' + escapeHtml(options.industry) : ''
  html = html.replace(
    '<title>Preview</title>',
    `<title>${escapeHtml(options.businessName)}${titleSuffix}</title>`
  )

  // 3. Add meta description after viewport meta tag
  const metaDescription = options.description || options.businessName + ' website'
  const metaDescriptionTag = `<meta name="description" content="${escapeHtml(metaDescription)}">`
  html = html.replace(
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    `<meta name="viewport" content="width=device-width, initial-scale=1.0">\n  ${metaDescriptionTag}`
  )

  // 4. Add Open Graph tags after meta description
  const ogTags = [
    `<meta property="og:title" content="${escapeHtml(options.businessName)}">`,
    `<meta property="og:description" content="${escapeHtml(options.description || '')}">`,
    `<meta property="og:type" content="website">`,
  ].join('\n  ')
  html = html.replace(
    metaDescriptionTag,
    `${metaDescriptionTag}\n  ${ogTags}`
  )

  // 5. Remove parent postMessage calls (standalone mode, not inside iframe)
  html = html.replace(
    /try\s*\{[^}]*window\.parent\.postMessage[^}]*\}\s*catch\s*\([^)]*\)\s*\{[^}]*\}/g,
    '/* standalone mode */'
  )

  // 6. Replace the dynamic runtime loader with inlined runtime script
  //    The loader is: (function() { var url = '...'; ... document.body.appendChild(s); })();
  const runtime = getRuntime()
  html = html.replace(
    /<script>\s*\/\/ Resolve runtime URL[\s\S]*?<\/script>/,
    `<script>\n${runtime}\n<\/script>`
  )

  return html
}
