import { constructHtmlBoilerplate } from '@/lib/utils/html-boilerplate'

export interface ExportOptions {
  businessName: string
  industry?: string
  description?: string
}

/**
 * Escapes special HTML characters for safe embedding in attributes and content.
 */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

/**
 * Builds a self-contained static HTML export from generated React code.
 *
 * Uses constructHtmlBoilerplate as the base (same as preview) to preserve
 * full React interactivity -- navigation toggles, scroll animations, form
 * handlers, modals, etc. Enhances with proper metadata for standalone use.
 */
export function buildStaticExport(generatedCode: string, options: ExportOptions): string {
  // Get the base HTML from the existing boilerplate (identical to preview)
  let html = constructHtmlBoilerplate(generatedCode)

  // 1. Add generated-by comment after DOCTYPE
  html = html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- Generated by WebGen -->')

  // 2. Replace the <title>Preview</title> with business name
  const titleSuffix = options.industry ? ' | ' + escapeHtml(options.industry) : ''
  html = html.replace(
    '<title>Preview</title>',
    `<title>${escapeHtml(options.businessName)}${titleSuffix}</title>`
  )

  // 3. Add meta description after viewport meta tag
  const metaDescription = options.description || options.businessName + ' website'
  const metaDescriptionTag = `<meta name="description" content="${escapeHtml(metaDescription)}">`
  html = html.replace(
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    `<meta name="viewport" content="width=device-width, initial-scale=1.0">\n  ${metaDescriptionTag}`
  )

  // 4. Add Open Graph tags after meta description
  const ogTags = [
    `<meta property="og:title" content="${escapeHtml(options.businessName)}">`,
    `<meta property="og:description" content="${escapeHtml(options.description || '')}">`,
    `<meta property="og:type" content="website">`,
  ].join('\n  ')
  html = html.replace(
    metaDescriptionTag,
    `${metaDescriptionTag}\n  ${ogTags}`
  )

  // 5. Remove parent postMessage calls (standalone mode, not inside iframe)
  html = html.replace(
    /try\s*\{[^}]*window\.parent\.postMessage[^}]*\}\s*catch\s*\([^)]*\)\s*\{[^}]*\}/g,
    '/* standalone mode */'
  )

  return html
}
